#!/bin/bash
#
# Write the `.itch.toml` that tells the itch.io app what to run.
#
# What the file is for: without it the app guesses which file in a build is the
# game, and on a payload with a shared library sitting beside the binary — which
# is what both the Linux and the Windows ones are — a guess is a coin toss that
# can land on SDL3.dll. With it there is one candidate and it is named. A plain
# browser download ignores the file, which is why each payload is also laid out
# so a human can see what to double-click.
#
# One script for both payloads that carry one — Linux and Windows; the macOS
# archive holds the bundle alone and needs no manifest — rather than the same four
# lines pasted into each. `name = "play"` is not a label, it is the word the app
# looks for to decide which action is the big button, and two hand-kept copies of
# a keyword is how one of them ends up spelled `start` and that platform ends up
# with no button at all.
set -euo pipefail

dir=${1:?usage: itch_manifest.sh STAGE_DIR PLAY_PATH}
play=${2:?usage: itch_manifest.sh STAGE_DIR PLAY_PATH}

if [ ! -d "$dir" ]; then
    echo "itch_manifest: no such directory: $dir" >&2
    exit 1
fi
if [ ! -e "$dir/$play" ]; then
    echo "itch_manifest: $dir has no $play to play" >&2
    exit 1
fi

cat >"$dir/.itch.toml" <<TOML
# Read by the itch.io app when it installs this build.
# Generated by packaging/itch_manifest.sh; do not edit here.
[[actions]]
name = "play"
path = "$play"
TOML
echo "itch_manifest: $dir/.itch.toml plays $play"
