#!/usr/bin/env python3
"""Generate a C translation unit containing the game's level source files."""

from pathlib import Path
import re
import sys


def natural_key(path: Path) -> list[object]:
    return [
        int(part) if part.isdigit() else part.lower()
        for part in re.split(r"(\d+)", path.as_posix())
    ]


def c_string(value: str) -> str:
    return '"' + value.replace("\\", "\\\\").replace('"', '\\"') + '"'


def byte_array(data: bytes) -> list[str]:
    lines = []
    for offset in range(0, len(data), 12):
        chunk = data[offset : offset + 12]
        lines.append("    " + ", ".join(f"0x{byte:02x}" for byte in chunk) + ",")
    return lines


def main() -> int:
    if len(sys.argv) < 3:
        print(
            f"usage: {Path(sys.argv[0]).name} OUTPUT LEVEL [LEVEL ...] "
            "[--sublevels SUBLEVEL ...]",
            file=sys.stderr,
        )
        return 2

    output = Path(sys.argv[1])
    values = sys.argv[2:]
    if "--sublevels" in values:
        split = values.index("--sublevels")
        level_values = values[:split]
        sublevel_values = values[split + 1 :]
    else:
        level_values = values
        sublevel_values = []
    levels = sorted((Path(value) for value in level_values), key=natural_key)
    sublevels = sorted(
        (Path(value) for value in sublevel_values), key=natural_key
    )
    if not levels:
        print("at least one campaign level is required", file=sys.stderr)
        return 2
    if not sublevels:
        print("at least one sublevel is required", file=sys.stderr)
        return 2

    lines = [
        "/* Generated by tools/embed_levels.py. Do not edit. */",
        '#include "embedded_levels.h"',
        "",
    ]
    all_sources = levels + sublevels
    for index, path in enumerate(all_sources):
        data = path.read_bytes()
        if not data:
            print(f"cannot embed empty level: {path}", file=sys.stderr)
            return 1
        lines.append(f"static const char embedded_level_{index}[] = {{")
        lines.extend(byte_array(data))
        lines.extend(["};", ""])

    lines.append("const EmbeddedLevelData EMBEDDED_LEVELS[] = {")
    for index, path in enumerate(levels):
        lines.append(
            "    {"
            f"{c_string(path.as_posix())}, embedded_level_{index}, "
            f"sizeof(embedded_level_{index})"
            "},"
        )
    lines.extend(
        [
            "};",
            "",
            "const size_t EMBEDDED_LEVEL_COUNT =",
            "    sizeof(EMBEDDED_LEVELS) / sizeof(EMBEDDED_LEVELS[0]);",
            "",
            "const EmbeddedLevelData EMBEDDED_SUBLEVELS[] = {",
        ]
    )
    for offset, path in enumerate(sublevels, start=len(levels)):
        lines.append(
            "    {"
            f"{c_string(path.as_posix())}, embedded_level_{offset}, "
            f"sizeof(embedded_level_{offset})"
            "},"
        )
    lines.extend(
        [
            "};",
            "",
            "const size_t EMBEDDED_SUBLEVEL_COUNT =",
            "    sizeof(EMBEDDED_SUBLEVELS) / sizeof(EMBEDDED_SUBLEVELS[0]);",
            "",
        ]
    )

    output.write_text("\n".join(lines), encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
