#!/usr/bin/env python3
"""Generate a C translation unit containing the game's level source files."""

from pathlib import Path
import re
import sys


def natural_key(path: Path) -> list[object]:
    return [
        int(part) if part.isdigit() else part.lower()
        for part in re.split(r"(\d+)", path.as_posix())
    ]


def c_string(value: str) -> str:
    return '"' + value.replace("\\", "\\\\").replace('"', '\\"') + '"'


def byte_array(data: bytes) -> list[str]:
    lines = []
    for offset in range(0, len(data), 12):
        chunk = data[offset : offset + 12]
        lines.append("    " + ", ".join(f"0x{byte:02x}" for byte in chunk) + ",")
    return lines


def main() -> int:
    if len(sys.argv) < 3:
        print(
            f"usage: {Path(sys.argv[0]).name} OUTPUT LEVEL [LEVEL ...]",
            file=sys.stderr,
        )
        return 2

    output = Path(sys.argv[1])
    levels = sorted((Path(value) for value in sys.argv[2:]), key=natural_key)

    lines = [
        "/* Generated by tools/embed_levels.py. Do not edit. */",
        '#include "embedded_levels.h"',
        "",
    ]
    for index, path in enumerate(levels):
        data = path.read_bytes()
        if not data:
            print(f"cannot embed empty level: {path}", file=sys.stderr)
            return 1
        lines.append(f"static const char embedded_level_{index}[] = {{")
        lines.extend(byte_array(data))
        lines.extend(["};", ""])

    lines.append("const EmbeddedLevelData EMBEDDED_LEVELS[] = {")
    for index, path in enumerate(levels):
        lines.append(
            "    {"
            f"{c_string(path.as_posix())}, embedded_level_{index}, "
            f"sizeof(embedded_level_{index})"
            "},"
        )
    lines.extend(
        [
            "};",
            "",
            "const size_t EMBEDDED_LEVEL_COUNT =",
            "    sizeof(EMBEDDED_LEVELS) / sizeof(EMBEDDED_LEVELS[0]);",
            "",
        ]
    )

    output.write_text("\n".join(lines), encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
